version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  app:
    image: dersoc/final_project:v1.5
    container_name: app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: todos
    ports:
      - "80:80"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
